[project]
name = "ox-game"
version = "0.1.0"
description = "Tic-tac-toe aka. ox_game"
readme = "README.md"
authors = [
    { name = "Q. ENNA", email = "61851857+weifeimo@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
ox-game = "ox_game:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
